spring.application.name=personalReminder
spring.datasource.url=jdbc:postgresql://localhost:5432/reminder
spring.datasource.username=thu.pa
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Important: Turn off auto-ddl due to using liquibase
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=K7gYb3XwZp9qR2mN8vT5jL1sC6dF4hA0eU3iO9wQ7yM=
jwt.expiration=86400
logging.level.org.springframework.security=DEBUG